name: Publish Gradle plugin to Gradle Plugins Portal

on:
  workflow_dispatch:
    inputs:
      cond_release:
        required: true
        description: 'Type "release" to release artifacts to Gradle Plugins Portal.'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish artifacts
        if: ${{ github.event.inputs.cond_release == 'release' }}
        run: ./gradlew clean :feature-flag:publishPlugin -Dgradle.publish.key="${{ secrets.GRADLE_PLUGIN_PORTAL_PUBLISH_KEY }}" -Dgradle.publish.secret="${{ secrets.GRADLE_PLUGIN_PORTAL_PUBLISH_SECRET }}"
